name = "toy_likelihood"
stan_file = "../src/stan/model_conc.stan"
data_folder = "../data/raw/toy_model_single_condition"
likelihood = true
analyse = {"pair" = {"testarg" = 1}}
devel = false
save_plot = true

[sample_kwargs]
chains = 2
parallel_chains = 4
sig_figs = 6
show_progress = true
iter_warmup = 4000
iter_sampling = 1000
max_treedepth = 12
adapt_delta = 0.9
refresh = 1