name = "toy_prior_conc"
stan_file = "src/stan/model_conc.stan"
data_folder = "data/raw/toy_model"
likelihood = false
analyse = true
devel = false
save_plot = true

[sample_kwargs]
chains = 2
parallel_chains = 2
sig_figs = 18
show_progress = true
iter_warmup = 2000
iter_sampling = 2000
max_treedepth = 12
adapt_delta = 0.90
refresh = 1
