name = "toy_likelihood"
stan_file = "src/stan/model_ff.stan"
data_folder = "data/raw/toy_model"
likelihood = true
run = true

[sample_kwargs]
chains = 2
show_progress = true
iter_warmup = 2000
iter_sampling = 1000
max_treedepth = 12
refresh = 1
adapt_delta = 0.999
