name = "toy_likelihood"
stan_file = "src/stan/model_conc.stan"
data_folder = "data/raw/toy_model"
likelihood = true
run = true

[sample_kwargs]
chains = 2
parallel_chains = 2
sig_figs = 18
show_progress = true
iter_warmup = 10000
iter_sampling = 2000
max_treedepth = 12
adapt_delta = 0.9
refresh = 1